site_name: Plugins
site_url: https://mrchickenx.github.io/plugin
repo_url: https://github.com/MrChickenX/plugin
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

copyright: Copyright &copy; 2025

extra_css:
  - stylesheets/extra.css
  - "https://fonts.googleapis.com/icon?family=Material+Icons"

extra_javascript:
  - javascripts/extra.js
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"

plugins:
  - tags
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  #- Plugins:
  - Lightpath:
    - Config: lightpath/config.md
    - Particles: lightpath/particles.md
  - Welcome Messages:
      - Config: welcomemessages/config.md
#        - Particles: lightpath/particles.md
#  - Features:
#      - Overview: features/overview.md
#      - Documentation: features/docs.md
#  - Reference:
#      - API: reference/api.md
#      - Configuration: reference/config.md
#  - Wiki:
#      - About: wiki/about.md
#      - Help: wiki/help.md
#