site_name: My Docs
site_url: https://sitename.example
repo_url: https://github.com/MrChickenX/plugin
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/git-alt
  favicon: fontawesome/solid/code
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

copyright: Copyright &copy; 2025

plugins:
  - git-committers:
      repository: MrChickenX/plugin
  - tags
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Lightpath:
      - Config: lightpath/config.md
      - Particles: lightpath/particles.md
#  - Features:
#      - Overview: features/overview.md
#      - Documentation: features/docs.md
#  - Reference:
#      - API: reference/api.md
#      - Configuration: reference/config.md
#  - Wiki:
#      - About: wiki/about.md
#      - Help: wiki/help.md
#